Define and extend ShouldPropagate in algorithm 3.2
w3f/polkadot-spec pull request #207
Opened 2020-06-01 14:59 UTC by lamafab

Fixes #180.

Printscreen:

![image](https://user-images.githubusercontent.com/42901763/83422019-38190680-a429-11ea-8570-ea6cdd290b18.png)

2020-06-30 13:00 UTC, drskalman requested changes
- I would also add a general human friendly description at the beginning of the transaction section explaining the duty of the node in propagating transaction after validation refering this algorithm.
- I would also make it more clear which peer you should gossip the transaction at either here or in the transaction message. I assume we only propagate to people we are not sure they have seen the transaction.

2020-06-30 13:00 UTC, drskalman commented on polkadot-host-spec/c03-transition.tm
> +
This does not make it clear what is the difference between "ShouldPropagate" and "Propagate" fields.

2020-07-06 19:01 UTC, lamafab commented
@drskalman -> **Updated**

>     * I would also add a general human friendly description at the beginning of the transaction section explaining the duty of the node in propagating transaction after validation refering this algorithm.

![image](https://user-images.githubusercontent.com/42901763/86629314-8478d880-bfcb-11ea-8a67-5d70494b546a.png)

>     * I would also make it more clear which peer you should gossip the transaction at either here or in the transaction message.

![image](https://user-images.githubusercontent.com/42901763/86629387-9fe3e380-bfcb-11ea-906b-3a0ab800efb1.png)

> I assume we only propagate to people we are not sure they have seen the transaction.

You're right:

```rust
	for (id, ref mut peer) in peers.iter_mut() {
		for (message_hash, topic, message) in messages.clone() {
			let intent = match intent {
				MessageIntent::Broadcast { .. } =>
					if peer.known_messages.contains(&message_hash) {
						continue;
					} else {
						MessageIntent::Broadcast
					},
				MessageIntent::PeriodicRebroadcast =>
					if peer.known_messages.contains(&message_hash) {
						MessageIntent::PeriodicRebroadcast
					} else {
						// peer doesn't know message, so the logic should treat it as an
						// initial broadcast.
						MessageIntent::Broadcast
					},
				other => other,
			};

			if !message_allowed(id, intent, &topic, &message) {
				continue;
			}

			peer.known_messages.insert(message_hash.clone());

			trace!(target: "gossip", "Propagating to {}: {:?}", id, message);
			network.write_notification(id.clone(), engine_id, message.clone());
		}
	}
```

2020-07-06 19:04 UTC, lamafab commented on polkadot-host-spec/c03-transition.tm
> +
The field `Propagate` (capitalized `propagate` -> I fixed it) refers to the data type returned by `TaggedTransactionQueue_validate_transaction`:

![image](https://user-images.githubusercontent.com/42901763/86629842-43cd8f00-bfcc-11ea-85a3-977c4ce37910.png)

2020-07-08 09:55 UTC, merged

2020-07-08 09:55 UTC, drskalman approved these changes