WIP: add initial install rules
w3f/polkadot-spec pull request #6
Opened 2019-04-04 17:38 UTC by fgimenez

2019-04-05 08:45 UTC, fgimenez commented
@drskalman ready for review, please let me know WDYT.

Following with the comments in #2, now the `CMakeList.txt` file for each of the rust testers should have only one call to `cargo_build(NAME <tester>)`, in `cargo_build` there's a call to `install()` with the proper values, the same values used during the build process. This call adds rules to the `install` target, which are used when calling `make install`.

I've also refactored a bit `cmake/CMakeCargo.cmake`, extracting the set up of the envirnment variables that depend on the platform to a separate function.

WRT the go tester, currently the build command is configured to write the output to the same path as the final destination in rust, so AIUI there's no need to add `install` rules.

Finally, I've added a call to `make install` to `build_test.sh`, so that we don't need to create a separate `install_test.sh` for it.

Any thoughts are more than welcome :) cheers!

2019-04-05 20:24 UTC, drskalman requested changes
Thanks a lot, few small changes and we should be good to merge.

2019-04-05 20:24 UTC, drskalman commented on cmake/CMakeCargo.cmake
> +  install(FILES ${LIB_COMPILED_FILE} DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
rather

    install(FILES ${LIB_COMPILED_FILE} DESTINATION bin)

is more standard

2019-04-05 20:24 UTC, drskalman commented on cmake/GolangSimple.cmake
> -  install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/${NAME} DESTINATION bin)
I would leave this line and then run 

     make DESTDIR=bin install  

then I'll adjust 
https://github.com/w3f/polkadot-re-tests/blob/0137463f3224a8150b29184e56eb00308987f922/test/test_fixtures.jl#L20
To point to the new correct location

    ../build/bin/usr/local/bin/scale_codec,
    ../build/bin/usr/local/bin/scale_codec_go

That's the standard behavoir of CMake with c++ which I'm gonig to add soon.

2019-04-08 07:28 UTC, fgimenez commented
@drskalman good points, done, I've taken the opportunity to add `DESTDIR=bin` to the `make install` call in `build_test.sh`, let me know WDYT.

2019-04-09 09:46 UTC, drskalman approved these changes

2019-04-09 09:49 UTC, merged