Controller keys deprecation
w3f/polkadot-spec pull request #700
Opened 2023-09-07 14:00 UTC by heversonbr

Tagged definition as deprecated and  removed controller keys information from other parts of the text due to deprecation

Handles issue:  https://github.com/w3f/polkadot-spec/issues/692

2023-09-07 14:17 UTC, bhargavbh requested changes
maybe link to the wiki explaining the stashing keys can be added at the appropriate place?

2023-09-07 14:58 UTC, Noc2 approved these changes
I removed: "The Stash key holds the majority of the users’ funds and should neither be shared with anyone, saved on an online device, nor used to submit extrinsics." (doesn't need to be part of the spec). Otherwise, feel free to merge

2023-09-08 10:54 UTC, Noc2 approved these changes

2023-09-08 11:25 UTC, bhargavbh approved these changes

2023-09-08 11:46 UTC, merged